### ISSUE TITLE
new breadcrumb not created if search-hit already there

### ISSUE THREAD

**Issue by MBcode** [earthcube/facetsearch#22]
looks like breadcrumbs are added when it ends up (re)including search results again. ;lower-priority

**Comment by valentinedwv** [comment]
Triage:
Presently using the list of currentResults, as a proxy for updates on the filters.
Cause, since results list did not change, update to list of selected filters is not updated.

List of active filters is not shared via the state.js object. 
If we move the active facets into the state.js object, this should trigger an update on the 'breadcrumbs'

**Comment by valentinedwv** [comment]
PR #31
